### ISSUE TITLE
How to show menu bar after accidentally hide it 

### ISSUE THREAD

**Issue by RangerPzy** [klaussinani/ao#110]
**Describe the solution you'd like**
English is my second language, so if I didn't make myself clear, just ask me for more details.

I accidentally hide the menu bar, and stuck trying to get it back.
As the title says, how to show menu bar after hide it?

**Comment by yalexaner** [comment]
You mean, after you've gone full screan?

If that's what you did, try to press F11.

**Comment by brianbert** [comment]
press alt

**Comment by RangerPzy** [comment]
> press alt

I'm using Archlinux and i3-wm ,alt works for me, thank you very much!!
