### ISSUE TITLE
Export todo item list to text file 

### ISSUE THREAD

**Issue by MostHated** [klaussinani/ao#129]
It would be great if the app could have the ability to export out a single text list of todo items.

I have a Rainmeter skin I wanted to use [[Seen here](https://www.deviantart.com/livinglightningrod/art/Myriad-Notes-154346467?d=37&modal=welcomeback)] that has a small mouse over section that when displaying shows a list of notes, which read from a text file, 1 line per item, so if I could export out my current list from here automatically, it would be picked up and refreshed by my other app and can be displayed on my desktop as a small hud at all times.

**Comment by pythonInRelay** [comment]
No one uses rainmeter any more unless they've been stuck inside a time machine :p

Also you'd have to talk to Microsoft about allowing this. This is just an electron wrapper.

**Comment by MostHated** [comment]
![](https://i.imgur.com/lQCXtDC.png)
