### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by gookcedemir** [klaussinani/ao#149]
**Describe the solution you'd like**
It would be really nice to have a GitHub connection. So I would have tasks that automatically created in my to-do list.

* Issue assignees
* Pull-request assignies

**Comment by pythonInRelay** [comment]
This has not been updated since well before Dec 2019. It most likely won't see any future updates either.

If you want such a feature I suggest creating it yourself using my updated branch [here](https://github.com/pythonInRelay/ao).
