### ISSUE TITLE
List Navigation in Mac

### ISSUE THREAD

**Issue by jinxuan** [klaussinani/ao#42]
**Describe the bug**
List Navigation is not working in Mac

**To Reproduce**
Install mac app, press cmd + 1-9, nothing happened.

**Expected behavior**
Jump to specific list.

**Screenshots**
<img width="273" alt="xnip2018-09-12_17-07-36" src="https://user-images.githubusercontent.com/5571773/45459698-66334180-b6ae-11e8-92a3-9f8995f69b2c.png">

**Technical Info (please complete the following information)**
 - OS: Mac
 - Ao Version: 5.6.0

**Additional context**

**Comment by klaussinani** [comment]
Issue fixed on f25061c. 
New 6.0.0 release is now out. Full changelog & binaries are available on the [GitHub Releases page](https://github.com/klaussinani/ao/releases/tag/v6.0.0).
