### ISSUE TITLE
New Microsoft To-Do Interface

### ISSUE THREAD

**Issue by Modelmat** [klaussinani/ao#43]
**Describe the bug**
The new Microsoft To-Do interface breaks the File | Edit menu functionality

**To Reproduce**
Open up Ao, try to use menu buttons.

**Expected behavior**
The menu buttons work.

**Screenshots**

![image](https://user-images.githubusercontent.com/25718989/45741389-ca1fb200-bc3a-11e8-9582-dcfd08cbc3dd.png)

**Technical Info (please complete the following information)**
 - OS: Linux desktop 4.18.7-1-MANJARO 
 - Ao Version: 5.6.0-1

**Additional context**

**Comment by aksh1618** [comment]
The themes are broken too, as a result of this change

**Comment by Stele77** [comment]
Yeah, themes are broken too for me... Any fix in sight?

**Comment by klaussinani** [comment]
New 6.0.0 release, supporting the updated Microsoft To-Do interface, is now out. Full changelog & binaries are available on the [GitHub Releases page](https://github.com/klaussinani/ao/releases/tag/v6.0.0).
