### ISSUE TITLE
App offers new version even when I'm already using the newest version

### ISSUE THREAD

**Issue by mtrovo** [klaussinani/ao#49]
**Describe the bug**
I'm currently using the version 5.6.0 and keep getting a message asking me to upgrade to the new version 5.6.0.

**To Reproduce**
Check the code on tag v5.6.0.
`npm run start`
Click on Help > Check for Update
A message offering the download of version v5.6.0 is going to appear.

**Expected behavior**
It should show that I'm on the latest version

**Screenshots**
N/A

**Technical Info (please complete the following information)**
 - OS: MacOS 10.14.1 (18B75)
 - Ao Version: 5.6.0

**Additional context**
While debugging the issue I found that it's related to commit 1306741, the old update URLs are giving 404 and the code at update.js handle any status code not 200 this way.

I suggest to release a new version 5.7.0, this should keep showing the nag massage to old users but when they click on the update link they will be redirected to a new version that checks for update on the correct URL.

**Comment by TimCook1** [comment]
Just wanted to echo the above comment.  This happens on all my OSX systems - and given there's no way to outright disable checking for updates, the spurious message is getting annoying.

**Comment by mtrovo** [comment]
Meanwhile I'm using a version that I built locally from `master` and it fixes the annoying popup issue.

**Comment by muojp** [comment]
It's because the new version SHOULD be available due to the repo-migration: https://github.com/klaussinani/ao/commit/13067410936f7a3bf4df084b915be967985a3b87#diff-971ef271c5851a3f095f55430133aa91
v5.6.0 people (incl. me) still access https://klauscfhq.github.io/ao/update.json only to get empty result and it leads us the 
https://github.com/klaussinani/ao/blob/master/update.js#L70 check to prompt new '' (empty) version available.

**Comment by muojp** [comment]
@klaussinani could you please consider bumping version?

**Comment by muojp** [comment]
@klaussinani hi, I'm still getting new-version alert periodically. Could you take a look on https://github.com/klaussinani/ao/issues/49#issuecomment-443153523 when you have time please?

**Comment by klaussinani** [comment]
Issue fixed on 3029ae0. New 6.0.0 release is out. Full changelog & binaries are available on the [GitHub Releases page](https://github.com/klaussinani/ao/releases/tag/v6.0.0).
