### ISSUE TITLE
Links open in Ao window and in default browser

### ISSUE THREAD

**Issue by Modelmat** [klaussinani/ao#56]
**Describe the bug**
Clicking on links inside ao will open a second ao window to that URL and open another tab in my open browser.

**To Reproduce**
Add a link in the notes or a subtask, then click on it.

**Expected behavior**
The URL opens a new tab in a browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/25718989/50808922-f9c30900-1354-11e9-95de-5ef2e818d9f5.png)

**Technical Info (please complete the following information)**
 - OS: Arch Linux
 - Ao Version: 6.4.0

**Comment by klaussinani** [comment]
Nice catch! Thank you a lot for taking the time to report the issue : )
