### ISSUE TITLE
Ao Does not start.

### ISSUE THREAD

**Issue by schorschie** [klaussinani/ao#73]
**Describe the bug**
The App does not start at all, whereas I mean, that there is nothing showing up on the screen. When typing `ao` in the terminal, then it comes back to the promt after around one second without output.

**To Reproduce**
First I installed it with Ubuntu Software 3.28.1 and then I removed and installed it in the terminal with snap.

**Expected behavior**
Some splash screen, followed by an UI showing up on the screen.

**Screenshots**
![screenshot from 2019-02-10 10-54-25](https://user-images.githubusercontent.com/13631749/52532270-6483ad80-2d22-11e9-97f6-35df63e3bc72.png)

**Technical Info (please complete the following information)**
 - OS: Ubuntu 18.04.1 LTS
 - Ao Version:  stable:    6.8.0 2019-01-20 

**Additional context**

**Comment by llirrikk** [comment]
try ```snap run ao```

**Comment by schorschie** [comment]
thanks, but this issue was dealt with in the meanwhile. It is starting now.
