### ISSUE TITLE
Getting a blank form

### ISSUE THREAD

**Issue by elvogel** [klaussinani/ao#78]
I am getting a blank form whenever I try to open and run this app. 

**To Reproduce**
Not sure how to reproduce this - it's happening no matter what I do, even if I restart the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/2071112/53595737-08b38400-3b6c-11e9-8530-8b73f573ec67.png)

**Technical Info (please complete the following information)**
```
Version: 6.8.0
Electron: 3.1.1
Chrome: 66.0.3359.181
Node: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.18-surface-linux-surface
```

**Comment by KonTy** [comment]
It is so unfortunate I get this black form all the time but when I put it under the debugger it goes away. So I can't debug it, my suspicion though it is related to Authentication when it can't authenticate it shows a blank page. 

I think someone with more time and/or experience needs to look into this.

**Comment by novdddd** [comment]
looks like internet problem

**Comment by elvogel** [comment]
Internet problem confirmed. Whenever I turn on my VPN half the apps and Firefox stop working. Opening a ticket with them.

**Comment by Stele77** [comment]
It definitvely is NOT cause by VPN for me. Or Internet-Connection for this matter. On Firefox it loads not problem, with GNOME-Web (Epiphany) and chromium-based browsers it does NOT.
So some problem due to chromium engine?
