### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by cperezabo** [klaussinani/ao#79]
Dark theme and the rest of the themes are not working in macOS (latest version) with latest version of AO.

**Comment by Legio1221** [comment]
I can attest to this. Recently installed Ao and the themes are not working.

**Comment by novdddd** [comment]
Work fine on Windows and Linix 🤔

**Comment by XunGong99** [comment]
[
![Screenshot from 2019-03-22 20-58-13](https://user-images.githubusercontent.com/32933986/54824254-5c396d80-4ce5-11e9-8ac1-43e9dc8b2547.png)
](url)
In linux, I can not get night mode totally.

**Comment by rqmok** [comment]
On Mac OS, cannot switch to any other theme.
