### ISSUE TITLE
Seems broken on MacOS

### ISSUE THREAD

**Issue by yang** [klaussinani/ao#82]
**Describe the bug**
Seems to just be a wrapper around the web app.

**To Reproduce**
Just run ao and try to use it.

**Expected behavior**
I expect the UI to look like what's shown in the project screenshots, currently just looks like the official web app. I expect the menu commands to work. Etc.

**Screenshots**
https://youtu.be/EGHF0yNn_nk

**Technical Info (please complete the following information)**
 - OS: MacOS
 - Ao Version: 6.8.0

**Comment by novdddd** [comment]
Work ok in Windows and linux 🤔

**Comment by Georgesab** [comment]
Hi, also having this issue. None of the menu-bar options seem to be working. Especially disappointing as I'd love to be able to use dark mode.
---
macOS 10.14.3

**Comment by NickHeurter** [comment]
I have the exact same issue. It's a great application, but the shortcodes are needed in order to make it work more productive. Do you think you can solve this issue? :)

**Comment by rqmok** [comment]
I'm having the same issue. Cannot change the theme either.

**Comment by shadow00** [comment]
@klaussinani this issue is still there in version 6.9.0 on Windows
