### ISSUE TITLE
Feature request : Hide topbar icon

### ISSUE THREAD

**Issue by fakhamatia** [klaussinani/ao#85]
Option to hide topbar icon

**Comment by novdddd** [comment]
`View` > `Toggle Menu Bar`

**Comment by fakhamatia** [comment]
![Screenshot from 2019-04-29 18-51-27](https://user-images.githubusercontent.com/20030910/56902688-0ad48900-6ab0-11e9-96ee-ecc1f88b3684.png)

**Comment by novdddd** [comment]
Check #87
