### ISSUE TITLE
Disable the Are you sure you want to Exit Dialog

### ISSUE THREAD

**Issue by Modelmat** [klaussinani/ao#88]
**Is your feature request related to a problem? Please describe.**
When right-clicking on the tray icon > exit ao, it asks "are you sure you want to exit". This is highly irritating.

**Describe the solution you'd like**
Close immediately with no confirmation.

**Additional context**
![image](https://user-images.githubusercontent.com/25718989/56876965-36467c00-6a8e-11e9-8bdb-68f0f76066d0.png)

**Comment by novdddd** [comment]
`File` > `Request Exit Confirmation`
Search a bitt before creating issue 😜

**Comment by Modelmat** [comment]
I thought I did. Must've only looked in `View`, wouldn't expect this to be in `File`.
